app = "mumble-afkbot"

[build]
  dockerfile = "docker/Dockerfile"

[env]
  AFK_CHANNEL="AFK"
  SERVER="mumble.example.compile"
  PORT="64738"
  NICK="afkbot"
  CERTIFICATE="certs/cert.pem"
  IDLE_TIME="15"
